"""current_url finding funcs and trig

Revision ID: 0fe4d91dd7e6
Revises: ca69f584cfac
Create Date: 2022-06-24 00:13:03.596054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe4d91dd7e6'
down_revision = 'ca69f584cfac'
branch_labels = None
depends_on = None


curr_min_distance = '''
CREATE OR REPLACE FUNCTION curr_min_distance(lat NUMERIC, lon NUMERIC) RETURNS INTEGER AS
$$
DECLARE url_id INTEGER;
BEGIN
	WITH distances AS (
	SELECT u.id as u_id, 3963 * ACOS(SIN(gp.latitude) * SIN($1) + COS(gp.latitude) * COS($1) * COS($2 - gp.longitude)) AS dist FROM data_urls u
	INNER JOIN global_positions gp
	ON u.global_position_id = gp.id WHERE u.data_type = 'current'
	) SELECT u_id FROM distances WHERE dist = (SELECT MIN(dist) FROM distances) INTO url_id;
	RETURN url_id;
END;
$$
LANGUAGE PLPGSQL;
                    '''
                    
find_nearest_curr = '''
CREATE OR REPLACE FUNCTION find_nearest_curr() RETURNS TRIGGER AS
$$
DECLARE url_id INTEGER;
DECLARE lat NUMERIC;
DECLARE lon NUMERIC;
BEGIN
	 
 	SELECT gp.latitude, gp.longitude FROM global_positions gp
 	WHERE NEW.global_position_id = gp.id INTO lat, lon;
 	SELECT * FROM curr_min_distance(lat, lon) INTO url_id;
 	NEW.current_url_id = url_id;
 	RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;
                    '''


trigger = '''
              CREATE TRIGGER set_nearest_curr
              BEFORE INSERT ON fishing_spots
              FOR ROW EXECUTE FUNCTION find_nearest_curr();
           '''


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ADDED MANUALLY 6/23/2022
    op.execute(curr_min_distance)
    op.execute(find_nearest_curr)
    op.execute(trigger)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ADDED MANUALLY 6/23/2022
    op.execute('DROP TRIGGER IF EXISTS set_nearest_curr ON fishing_spots CASCADE;')
    op.execute('DROP FUNCTION find_nearest_curr')
    op.execute('DROP FUNCTION curr_mind_distance')
    # ### end Alembic commands ###
