"""add is_public to spot

Revision ID: 1d008b00da5a
Revises: a7968a83daf2
Create Date: 2022-06-20 19:04:11.427411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d008b00da5a'
down_revision = 'a7968a83daf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishing_spots', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fishing_spots', 'is_public')
    # ### end Alembic commands ###
