"""Create dataurl table

Revision ID: 3d3758b43ee8
Revises: 4ebe3caeaf57
Create Date: 2022-06-20 15:01:34.609925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3758b43ee8'
down_revision = '4ebe3caeaf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('query_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'query_data')
    )
    op.add_column('fishing_spots', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('fishing_spots', sa.Column('weather_url_id', sa.Integer(), nullable=True))
    op.add_column('fishing_spots', sa.Column('current_url_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fishing_spots', 'data_urls', ['current_url_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fishing_spots', 'data_urls', ['weather_url_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fishing_spots', type_='foreignkey')
    op.drop_constraint(None, 'fishing_spots', type_='foreignkey')
    op.drop_column('fishing_spots', 'current_url_id')
    op.drop_column('fishing_spots', 'weather_url_id')
    op.drop_column('fishing_spots', 'nickname')
    op.drop_table('data_urls')
    # ### end Alembic commands ###
