"""initial db

Revision ID: 4ebe3caeaf57
Revises: 
Create Date: 2022-06-20 13:27:56.805442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebe3caeaf57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angler_spots',
    sa.Column('angler_id', sa.Integer(), nullable=False),
    sa.Column('fishing_spot_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['angler_id'], ['anglers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fishing_spot_id'], ['fishing_spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('angler_id', 'fishing_spot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('angler_spots')
    # ### end Alembic commands ###
