"""add spot_related_pos delete trigger

Revision ID: 5dd8fcaf961b
Revises: 713ea928a80b
Create Date: 2022-06-22 21:34:16.800309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd8fcaf961b'
down_revision = '713ea928a80b'
branch_labels = None
depends_on = None



find_nearest_current = '''
                           CREATE FUNCTION find_nearest()
                           RETURNS TRIGGER AS $$
                           BEGIN
                               WITH distances AS (
                                   SELECT id,
                                   MIN(3963 * ACOS(SIN(cs.latitude) * SIN(NEW.latitude) + 
                                                COS(cs.latitude) * COS(NEW.latitude) *
                                                COS(NEW.latitude - cs.latitude)
                                               )
                                    ) AS dist FROM current_stations cs
                                ) INSERT INTO fishing_spots (nearest_known_id)
                                  SELECT id FROM distances WHERE dist=(SELECT MIN(dist) from distances);
                           RETURN NEW;
                           END;
                           $$ LANGUAGE PLPGSQL;
                    '''

trigger = '''
              CREATE TRIGGER insert_nearest
              AFTER INSERT ON fishing_spots
              FOR EACH ROW EXECUTE FUNCTION find_nearest();
          '''


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_related_positions',
    sa.Column('fishing_spot_id', sa.Integer(), nullable=False),
    sa.Column('global_position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fishing_spot_id'], ['fishing_spots.id'], ),
    sa.ForeignKeyConstraint(['global_position_id'], ['global_positions.id'], ),
    sa.PrimaryKeyConstraint('fishing_spot_id', 'global_position_id')
    )
    
    # ADDED MANUALLY 6/22/2022
    op.execute('DROP TRIGGER IF EXISTS insert_nearest ON fishing_spots CASCADE;')
    op.execute('DROP FUNCTION find_nearest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_related_positions')
    
    # ADDED MANUALLY 6/22/2022
    op.execute(find_nearest_current)
    op.execute(trigger)
    # ### end Alembic commands ###
