"""drop unique constr global_pos

Revision ID: 713ea928a80b
Revises: ae414c86c19c
Create Date: 2022-06-22 00:42:45.929452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713ea928a80b'
down_revision = 'ae414c86c19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('global_positions_latitude_longitude_key', 'global_positions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('global_positions_latitude_longitude_key', 'global_positions', ['latitude', 'longitude'])
    # ### end Alembic commands ###
