"""fix cascade on delete

Revision ID: 8fe8c0101ec3
Revises: 9d986a3f0aff
Create Date: 2022-06-28 00:21:10.893321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe8c0101ec3'
down_revision = '9d986a3f0aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('angler_baits_angler_id_fkey', 'angler_baits', type_='foreignkey')
    op.drop_constraint('angler_baits_bait_id_fkey', 'angler_baits', type_='foreignkey')
    op.create_foreign_key('angler_baits_angler_id_fkey', 'angler_baits', 'anglers', ['angler_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('angler_baits_bait_id_fkey', 'angler_baits', 'baits', ['bait_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('angler_fishing_spots_angler_id_fkey', 'angler_fishing_spots', type_='foreignkey')
    op.drop_constraint('angler_fishing_spots_fishing_spot_id_fkey', 'angler_fishing_spots', type_='foreignkey')
    op.create_foreign_key('angler_fishing_Spots_angler_id_fkey', 'angler_fishing_spots', 'anglers', ['angler_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('angler_fishing_spots_fishing_spot_id_fkey', 'angler_fishing_spots', 'fishing_spots', ['fishing_spot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('angler_gear_angler_id_fkey', 'angler_gear', type_='foreignkey')
    op.drop_constraint('angler_gear_fishing_gear_id_fkey', 'angler_gear', type_='foreignkey')
    op.create_foreign_key('angler_gear_angler_id_fkey', 'angler_gear', 'anglers', ['angler_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('angler_gear_fishing_gear_id_fkey', 'angler_gear', 'fishing_gear', ['fishing_gear_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('angler_outings_fishing_outing_id_fkey', 'angler_outings', type_='foreignkey')
    op.drop_constraint('angler_outings_angler_id_fkey', 'angler_outings', type_='foreignkey')
    op.create_foreign_key('angler_outings_fishing_outing_id_fkey', 'angler_outings', 'fishing_outings', ['fishing_outing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('angler_outings_angler_id_fkey', 'angler_outings', 'anglers', ['angler_id'], ['id'], ondelete='CASCADE')
    op.drop_index('data_urls_hash_index', table_name='data_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('data_urls_hash_index', 'data_urls', ['data_type'], unique=False)
    op.drop_constraint('angler_outings_angler_id_fkey', 'angler_outings', type_='foreignkey')
    op.drop_constraint('angler_outings_fishing_outing_id_fkey', 'angler_outings', type_='foreignkey')
    op.create_foreign_key('angler_outings_angler_id_fkey', 'angler_outings', 'anglers', ['angler_id'], ['id'])
    op.create_foreign_key('angler_outings_fishing_outing_id_fkey', 'angler_outings', 'fishing_outings', ['fishing_outing_id'], ['id'])
    op.drop_constraint('angler_gear_fishing_gear_id_fkey', 'angler_gear', type_='foreignkey')
    op.drop_constraint('angler_gear_angler_id_fkey', 'angler_gear', type_='foreignkey')
    op.create_foreign_key('angler_gear_fishing_gear_id_fkey', 'angler_gear', 'fishing_gear', ['fishing_gear_id'], ['id'])
    op.create_foreign_key('angler_gear_angler_id_fkey', 'angler_gear', 'anglers', ['angler_id'], ['id'])
    op.drop_constraint('angler_fishing_spots_fishing_spot_id_fkey', 'angler_fishing_spots', type_='foreignkey')
    op.drop_constraint('angler_fishing_Spots_angler_id_fkey', 'angler_fishing_spots', type_='foreignkey')
    op.create_foreign_key('angler_fishing_spots_fishing_spot_id_fkey', 'angler_fishing_spots', 'fishing_spots', ['fishing_spot_id'], ['id'])
    op.create_foreign_key('angler_fishing_spots_angler_id_fkey', 'angler_fishing_spots', 'anglers', ['angler_id'], ['id'])
    op.drop_constraint('angler_baits_bait_id_fkey', 'angler_baits', type_='foreignkey')
    op.drop_constraint('angler_baits_angler_id_fkey', 'angler_baits', type_='foreignkey')
    op.create_foreign_key('angler_baits_bait_id_fkey', 'angler_baits', 'baits', ['bait_id'], ['id'])
    op.create_foreign_key('angler_baits_angler_id_fkey', 'angler_baits', 'anglers', ['angler_id'], ['id'])
    # ### end Alembic commands ###
