"""add column data_type to data_urls

Revision ID: 981fb243334b
Revises: 5dd8fcaf961b
Create Date: 2022-06-22 21:52:41.505167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981fb243334b'
down_revision = '5dd8fcaf961b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_urls', sa.Column('data_type', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_urls', 'data_type')
    # ### end Alembic commands ###
