"""DataUrl changed Spots

Revision ID: a7968a83daf2
Revises: 2de96c2c4ad0
Create Date: 2022-06-20 17:34:49.249457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7968a83daf2'
down_revision = '2de96c2c4ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('query_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'query_data')
    )
    op.create_table('angler_spots',
    sa.Column('angler_id', sa.Integer(), nullable=False),
    sa.Column('fishing_spot_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['angler_id'], ['anglers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fishing_spot_id'], ['fishing_spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('angler_id', 'fishing_spot_id')
    )
    op.create_foreign_key(None, 'fished_spots', 'fishing_spots', ['fishing_spot_id'], ['id'])
    op.create_foreign_key(None, 'fishes', 'fishing_spots', ['fishing_spot_id'], ['id'])
    op.create_foreign_key(None, 'fishing_conditions', 'fishing_spots', ['fishing_spot_id'], ['id'], ondelete='CASCADE')
    op.add_column('fishing_spots', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('fishing_spots', sa.Column('weather_url_id', sa.Integer(), nullable=True))
    op.add_column('fishing_spots', sa.Column('current_url_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fishing_spots', 'data_urls', ['weather_url_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fishing_spots', 'data_urls', ['current_url_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fishing_spots', type_='foreignkey')
    op.drop_constraint(None, 'fishing_spots', type_='foreignkey')
    op.drop_column('fishing_spots', 'current_url_id')
    op.drop_column('fishing_spots', 'weather_url_id')
    op.drop_column('fishing_spots', 'nickname')
    op.drop_constraint(None, 'fishing_conditions', type_='foreignkey')
    op.drop_constraint(None, 'fishes', type_='foreignkey')
    op.drop_constraint(None, 'fished_spots', type_='foreignkey')
    op.drop_table('angler_spots')
    op.drop_table('data_urls')
    # ### end Alembic commands ###
