"""big changes for global positions

Revision ID: ae414c86c19c
Revises: d758cf5a0055
Create Date: 2022-06-21 23:41:00.406949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae414c86c19c'
down_revision = 'd758cf5a0055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude')
    )
    op.add_column('current_stations', sa.Column('global_position_id', sa.Integer(), nullable=False))
    op.drop_constraint('current_stations_current_url_id_fkey', 'current_stations', type_='foreignkey')
    op.drop_constraint('current_stations_map_url_id_fkey', 'current_stations', type_='foreignkey')
    op.create_foreign_key(None, 'current_stations', 'global_positions', ['global_position_id'], ['id'])
    op.drop_column('current_stations', 'map_url_id')
    op.drop_column('current_stations', 'latitude')
    op.drop_column('current_stations', 'longitude')
    op.drop_column('current_stations', 'current_url_id')
    op.add_column('data_urls', sa.Column('global_position_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_urls', 'global_positions', ['global_position_id'], ['id'])
    op.add_column('fishing_spots', sa.Column('global_position_id', sa.Integer(), nullable=False))
    op.drop_constraint('fishing_spots_latitude_longitude_key', 'fishing_spots', type_='unique')
    op.drop_constraint('fishing_spots_current_station_id_fkey', 'fishing_spots', type_='foreignkey')
    op.drop_constraint('fishing_spots_weather_url_id_fkey', 'fishing_spots', type_='foreignkey')
    op.create_foreign_key(None, 'fishing_spots', 'global_positions', ['global_position_id'], ['id'])
    op.drop_column('fishing_spots', 'latitude')
    op.drop_column('fishing_spots', 'weather_url_id')
    op.drop_column('fishing_spots', 'longitude')
    op.drop_column('fishing_spots', 'current_station_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishing_spots', sa.Column('current_station_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fishing_spots', sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('fishing_spots', sa.Column('weather_url_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fishing_spots', sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fishing_spots', type_='foreignkey')
    op.create_foreign_key('fishing_spots_weather_url_id_fkey', 'fishing_spots', 'data_urls', ['weather_url_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fishing_spots_current_station_id_fkey', 'fishing_spots', 'current_stations', ['current_station_id'], ['id'])
    op.create_unique_constraint('fishing_spots_latitude_longitude_key', 'fishing_spots', ['latitude', 'longitude'])
    op.drop_column('fishing_spots', 'global_position_id')
    op.drop_constraint(None, 'data_urls', type_='foreignkey')
    op.drop_column('data_urls', 'global_position_id')
    op.add_column('current_stations', sa.Column('current_url_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('current_stations', sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('current_stations', sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('current_stations', sa.Column('map_url_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'current_stations', type_='foreignkey')
    op.create_foreign_key('current_stations_map_url_id_fkey', 'current_stations', 'data_urls', ['map_url_id'], ['id'])
    op.create_foreign_key('current_stations_current_url_id_fkey', 'current_stations', 'data_urls', ['current_url_id'], ['id'], ondelete='CASCADE')
    op.drop_column('current_stations', 'global_position_id')
    op.drop_table('global_positions')
    # ### end Alembic commands ###
