"""named fks add current_url_id fk to spots

Revision ID: ca69f584cfac
Revises: cf4d5731941b
Create Date: 2022-06-23 21:20:27.054056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca69f584cfac'
down_revision = 'cf4d5731941b'
branch_labels = None
depends_on = None






def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishing_spots', sa.Column('current_url_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fishing_spots_current_url_id_fkey', 'fishing_spots', 'data_urls', ['current_url_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fishing_spots_current_url_id_fkey', 'fishing_spots', type_='foreignkey')
    op.drop_column('fishing_spots', 'current_url_id')
    # ### end Alembic commands ###
