"""add data_type to data_urls

Revision ID: cf4d5731941b
Revises: 421b9f1ec5d2
Create Date: 2022-06-23 20:19:17.330283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4d5731941b'
down_revision = '421b9f1ec5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_urls', sa.Column('data_type', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_urls', 'data_type')
    # ### end Alembic commands ###
