"""drop query_string from data_urls

Revision ID: d758cf5a0055
Revises: 1b852d64770d
Create Date: 2022-06-21 22:56:40.074949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd758cf5a0055'
down_revision = '1b852d64770d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_urls', 'query_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('data_urls_url_query_data_key', 'data_urls', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('data_urls_url_query_data_key', 'data_urls', ['url', 'query_data'])
    op.alter_column('data_urls', 'query_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
